const { URL } = require('url')
const R = require('ramda')
const { Future } = require('ramda-fantasy')
const { Page, PageView, Domain, User, UserSession, Account } = require('../../models')
const SessionMonad = require('../user/interfaces')
